use std::fs;
use std::io::Write;
#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;
use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::app_spec::{layout_id, parse_app_spec};

const SHIMS_SUBDIR: &str = "shims";

pub(crate) fn shims_dir(home: &Path) -> std::path::PathBuf {
    home.join(SHIMS_SUBDIR)
}

pub(crate) fn shim_init(home: &Path) -> Result<()> {
    let dir = shims_dir(home);
    fs::create_dir_all(&dir).with_context(|| format!("failed to create {}", dir.display()))?;
    println!("{}", dir.display());
    Ok(())
}

pub(crate) fn shim_path_line(home: &Path) {
    println!("export PATH=\"{}:$PATH\"", shims_dir(home).display());
}

pub(crate) fn shim_add(home: &Path, app: &str, as_name: Option<&str>) -> Result<()> {
    #[cfg(unix)]
    {
        shim_init(home)?;
        let spec = parse_app_spec(app);
        let shim_name: String = as_name
            .map(str::to_string)
            .unwrap_or_else(|| layout_id(&spec));
        if shim_name.is_empty() || shim_name.contains('/') {
            bail!("invalid shim name `{shim_name}`");
        }

        let bmx = std::env::current_exe().context("failed to locate bmx executable for shim")?;
        let path = shims_dir(home).join(&shim_name);
        let mut f = fs::OpenOptions::new()
            .create(true)
            .write(true)
            .truncate(true)
            .mode(0o755)
            .open(&path)
            .with_context(|| format!("failed writing {}", path.display()))?;

        writeln!(
            f,
            "#!/usr/bin/env sh\n# generated by bmx shim add\nexec \"{}\" exec {} \"$@\"\n",
            bmx.display(),
            shell_escape_app_arg(app)
        )
        .with_context(|| format!("failed writing {}", path.display()))?;

        println!("installed shim {}", path.display());
        return Ok(());
    }
    #[cfg(not(unix))]
    {
        let _ = (home, app, as_name);
        bail!("`bmx shim add` is only supported on Unix targets");
    }
}

#[cfg(unix)]
fn shell_escape_app_arg(app: &str) -> String {
    // Safe embedding: wrap in single quotes, escape existing quotes.
    let mut s = String::with_capacity(app.len() + 2);
    s.push('\'');
    for ch in app.chars() {
        if ch == '\'' {
            s.push_str("'\"'\"'");
        } else {
            s.push(ch);
        }
    }
    s.push('\'');
    s
}
